name: Build StartUp on Macos

on:
  # Runs on pushes targeting the default branch
  merge:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write


# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Build job
  build-on-Macos-latest:
    runs-on: macos-latest
    steps:
      - name: Install Lua
        run: |
          brew install lua

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build in Macos
        run: |
          mkdir build
          cd build
          cmake ..
          make
